### ISSUE TITLE
Demo Online!

### ISSUE THREAD

**Issue by fasvald** [tpiros/advanced-chat#22]
Dude!
Can u deploy demo online because I cant build your project!

**Comment by Egorvoz** [comment]
And CSS crash and problem with socket io

**Comment by benyb9** [comment]
Dude! can you not use internet you noob

**Comment by tamaspiros** [comment]
Try to build it now - I have removed 2 lines from package.json. Now you need to do:
* `npm install`
* `bower install`
* `node server.js`

and it should work

**Comment by tamaspiros** [comment]
I currently don't have a space to store this demo. Maybe sometime soon.

**Comment by orangemn6** [comment]
@tpiros you could host it on render.com or heroku
