### ISSUE TITLE
Chat does not work

### ISSUE THREAD

**Issue by FabioS82** [tpiros/advanced-chat#39]
Hello, I am new in this area, and I'm trying to try this script, but it does me is working is so, is it could help me?

![bepqqxp](https://cloud.githubusercontent.com/assets/18095638/14063894/a27e2850-f3e0-11e5-9687-6678639182fb.png)

![screenshot_4](https://cloud.githubusercontent.com/assets/18095638/14063896/b6070586-f3e0-11e5-97b5-2ff4f2c5b87b.png)

**Comment by Shivamnema05** [comment]
Same issue.

**Comment by tpiros** [comment]
Can you provide me with some logs? Node.js logs - Browser (Developer tools) logs etc

**Comment by Shivamnema** [comment]
![image](https://cloud.githubusercontent.com/assets/11815650/25555566/9ae7bbd6-2d07-11e7-9645-6c1171682f73.png)
![image](https://cloud.githubusercontent.com/assets/11815650/25555571/ac9fe092-2d07-11e7-83ef-53de3c8c53ba.png)
